apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: controller
  namespace: skabashn-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:EcYht-controller
        name: container-image
        resources: {}
status: {}
