apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: spi
  name: controller
  namespace: skabashn-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: controller
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:5ba0b0340916f5a9061ccc34b59391e14f0f5e28eb3905e648d9da2e4f382983
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
