apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: spi
  name: controller
  namespace: skabashn-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: controller
    weight: 100
status: {}
