apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: oauth
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oauth
    app.kubernetes.io/part-of: spi
  name: oauth
  namespace: skabashn-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: oauth
    weight: null
status: {}
